<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Book_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get book by id
     */
    function get_book($id,$user_id)
    {

      $this->db->where('id', $id);
      $this->db->where('user_id', $user_id);
      return $this->db->get('book')->row_array();


    }

    /*
     * Get book by category
     */
    function get_books_cat_id($id)
    {

      $this->db->where('category', $id);
      $this->db->order_by('sortingcat', 'ASC');
      return $this->db->get('book')->result_array();


    }

    /*
     * Get all book
     */
    function get_all_book()
    {
        $this->db->order_by('sorting', 'ASC');
        return $this->db->get('book')->result_array();
    }



///  взять только закладки 1 пользователя index
    function get_all_book_one_user($user_id)
    {
        $this->db->where('user_id', $user_id);
        $this->db->order_by('sorting', 'ASC');
        return $this->db->get('book')->result_array();
    }
//колво -записей
    function get_last_book_index($user_id)
    {
        $this->db->where('user_id', $user_id);
        return $this->db->count_all_results('book');
    }
///  взять только закладки 1 пользователяindex





/// взять только закладки 1 пользователя по категориям
    function get_all_book_serch_one_user($user_id, $serch_category)
    {
        $this->db->where('user_id', $user_id);
        $this->db->where('category', $serch_category);
        //$this->db->order_by('dtime', 'DESC');//dtime
        $this->db->order_by('sortingcat', 'ASC');
        return $this->db->get('book')->result_array();
    }




    /*
     * function to add new book
     */
    function add_book($params)
    {
        $this->db->insert('book',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update book
     */
    function update_book($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('book',$params);
    }

    /*
     * function to delete book
     */
    function delete_book($id)
    {
        return $this->db->delete('book',array('id'=>$id));
    }
}
