<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Savebook extends CI_Controller{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Listing of book
     */
    function index()
    {

    //  redirect('/');
    }

    function board($id)
    {
      //кеширование данных

      ///

      $this->load->model('Book_model');
      $this->load->model('Category_model');


      //подгрузили модель категорий

//проверить настройки пользователя, включена ли паблик страница
      $data['cat']= $this->Category_model->get_cat_hash($id);
      if($data['cat']['stattus'] == 1)
      {
        $data['book'] =$this->Book_model->get_books_cat_id($data['cat']['id']);
        $data['_view'] = 'book/savebook';
        $this->load->view('layouts/main_savebook',$data);
      }
      else
      {
        show_error('The board does not exist or not open.');
      }



    }



}
